### ISSUE TITLE
'NoneType' object has no attribute 'poll'

### ISSUE THREAD

**Issue by clrdls** [fizista/micropython-umqtt.simple2#12]
I got the error message: 'NoneType' object has no attribute 'poll' that occurred on line 89 of umqtt  simple2.py
I am using an ESP32 with micropython version 1.18
I need my ESP32 to continue operating even if the MQTT broker is not running. 
I got the above error when I unplugged the broker from the network and called check_msg() as part of a while loop.
Using simple.py the ESP32 would hang with no explanation as to why and required a hard reset when calling check_msg() so I was trying simple2.py
 
Hope someone can help.

**Comment by dgoadby** [comment]
I have an ESP32 system that uses umqttsimple.py. In my case I always connect before each MQTT send attempt. If my server was not contactable for any reason an OSERROR(-1) was generated which stopped the code execution. 

This is my patched version of the wait_msg() function. It is not perfect but, until a better exception mechanism is created, it will work. I hope this helps.

```
   # Wait for a single incoming MQTT message and process it.
    # Subscribed messages are delivered to a callback previously
    # set by .set_callback() method. Other (internal) MQTT
    # messages processed internally.
    # 20/10/2021, DVG, Patched to prevent OSERROR(-1) 
    def wait_msg(self):
        res = self.sock.read(1)
        self.sock.setblocking(True)
        if res is None or res == b"":  # DVG patch
            return None
        # if res == b"":
        #    raise OSError(-1)
        if res == b"\xd0":  # PINGRESP
            sz = self.sock.read(1)[0]
            assert sz == 0
            return None
        op = res[0]
        if op & 0xf0 != 0x30:
            return op
        sz = self._recv_len()
        topic_len = self.sock.read(2)
        topic_len = (topic_len[0] << 8) | topic_len[1]
        topic = self.sock.read(topic_len)
        sz -= topic_len + 2
        if op & 6:
            pid = self.sock.read(2)
            pid = pid[0] << 8 | pid[1]
            sz -= 2
        msg = self.sock.read(sz)
        self.cb(topic, msg)
        if op & 6 == 2:
            pkt = bytearray(b"\x40\x02\0\0")
            struct.pack_into("!H", pkt, 2, pid)
            self.sock.write(pkt)
        elif op & 6 == 4:
            assert 0

```

**Comment by fizista** [comment]
> I got the error message: 'NoneType' object has no attribute 'poll' that occurred on line 89 of umqtt simple2.py
> I am using an ESP32 with micropython version 1.18

I suppose the micropython API has changed. The last version of micropython I tested with this library was 1.3.

You probably just need to change the `uselect` library import to `select`.

**Comment by fizista** [comment]
There is a new version of the library, if the problem occurs, please let me know.
