### ISSUE TITLE
OSError: [Errno 104] ECONNRESET

### ISSUE THREAD

**Issue by DonCapitano99** [fizista/micropython-umqtt.simple2#16]
Hello :)

I'm trying to setup an MQTT Network.
- Broker Raspberry Pi4
- Publisher ESP32

I'm using the simple2.py on the ESP32.
My problem is the errorcode from the title.

Test.txt contains my main code on the ESP32
[Test.txt](https://github.com/fizista/micropython-umqtt.simple2/files/10529943/Test.txt)

The "ConnectWifi.connect() function connects the ESP32 to my Network. This part is working.

The detailed error-message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Test.py", line 13, in <module>
  File "simple_mqtt2.py", line 323, in connect
  File "simple_mqtt2.py", line 128, in _write
OSError: [Errno 104] ECONNRESET

I have no clue what's missing or what else has to be done.

Thanks for every help and suggestions :)

**Comment by UntriexTv** [comment]
I would also like to get some help with this. My code works but if i leave it idle for too long this error happens (Maybe few minutes).

**Comment by UntriexTv** [comment]
@DonCapitano99 Seems like I solved it by using the ping command every few seconds.

**Comment by fizista** [comment]
Maintaining a stable connection is on the developer's side. This library does not manage the Internet connection. When maintaining the connection, my other library umqtt.robust2 can help.
