### ISSUE TITLE
connectOSError: -202

### ISSUE THREAD

**Issue by mat-l** [fizista/micropython-umqtt.simple2#4]
**Describe the bug**
`File "/umqtt/simple2.py", line 53, in connectOSError: -202`

**To Reproduce**
I am using your example code from here (https://github.com/fizista/micropython-umqtt.simple2/blob/master/example_sub.py) to publish every 60 seconds a value to my MQTT broker.

```
def mqtt_pub(server="xx.xx.xx", pub_topic="", pub_value=""):
    c = MQTTClient("umqtt_client_pub", server)
    c.connect()
    time.sleep(.5)
    c.publish(pub_topic, str(pub_value))
    time.sleep(.5)
    c.disconnect()
```

After a while I am getting the connection error above and no mqtt message is  published anymore. Even though the function "mqtt_pub" is called every time.
Any ideas how I can avoid this error?

**Details (please complete the following information):**
 - Device board: ESP32
 - Micropython version: 1.13
 - Library version: simple2, I guess I am using the latest version as I just installed it via upip yesterday

**Comment by fizista** [comment]
Check if the server port 1883 is active, and if there is encryption on this port or not.

**Comment by mat-l** [comment]
Everything was active. Guess connecting and disconnecting everytime made some trouble after a while. I have switched to robust2 and I am now only connecting once in my mqtt communication class. Therefore the error is gone.

**Comment by elvis-epx** [comment]
It could be because the old sockets are not garbage-collected?
