### ISSUE TITLE
Second subscription gives exception 5 in simple2

### ISSUE THREAD

**Issue by hjgode** [fizista/micropython-umqtt.simple2#8]
I have following code on a m5stack Core2.

> t='mqttGenericBridge/#' # can only subscribe to one topic tree and only one MQTTClient allowed?
> t2='cmnd/#'
> c=_MQTTClient('m5core2','192.168.0.40',1883,'','',300)
> c.connect()
> c.set_callback(fun_mqtt_callback)
> c.set_callback_status(fun_mqtt_status_callback)
> 
> pid1=c.subscribe(topic=t,qos=1)
> pid2=c.subscribe(topic=t2,qos=1)
> ...
> def updateThread():
>    global c, bThreadsRun
>    while bThreadsRun:
>        time.sleep_ms(500)
>        c.wait_msg() #blocking call    
>   _thread.start_new_thread(updateThread, ())

As soon as a publish of second topic is received, there is an error in line c.wait_msg() for ' if pid in self.rcv_pids:' and raises a MQTTException(5) inside def check_msg(self):... As long as only published topics with first topic are received, there is no error.

            if pid in self.rcv_pids:
                self.last_cpacket = ticks_ms()
                self.rcv_pids.pop(pid)
                self.cbstat(pid, 1)
            else:
                raise MQTTException(5)

I worked around this using your robust2 MQTTClient.

I a second subscription not supported with simple2?

**Comment by fizista** [comment]
When using simple2, you have to handle communication errors yourself. 

It is difficult for me, based on the information provided, to say why this problem occurs.

The library was tested with mosquitto's mqtt server. For this server, communication was problem-free and multiple topics could be subscribed to. Check with this server to see if communication is correct.

**Comment by hjgode** [comment]
I am using mosquitto server.

For me the error seems to be that simple2 is looking for the pid in the
received packet and does not find the pid in the list of rcvd pids.

Anyway, I am fine in using robust2.
